### ISSUE TITLE
Prefer using open-source solvers wherever it makes sense

### ISSUE THREAD

**Issue by tkelman** [JuliaOpt/juliaopt-notebooks#10]
This helps making it more accessible for anyone to run the code directly, wherever the notebooks aren't using any solver-specific functionality.

I could send a few PR's for this, but it'd be by editing ipynb files in nano since I don't actually use IJulia myself.

**Comment by mlubin** [comment]
Which notebooks don't do this?

**Comment by tkelman** [comment]
Whoops, I'll admit to not having read all of them. If it's only https://github.com/JuliaOpt/juliaopt-notebooks/commit/d6104060e9838fdd8aa29940dea372c96a448575, then that's not merged in master yet so false alarm.

**Comment by IainNZ** [comment]
False alarm, but its a good general point
